extends:
- "@redhat-cloud-services/eslint-config-redhat-cloud-services"
- "plugin:cypress/recommended"
rules:
  rulesdir/forbid-pf-relative-imports: off
  no-only-tests/no-only-tests: 'error'
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
      destructuredArrayIgnorePattern: "^_"
plugins:
  - "no-only-tests"
